### ISSUE TITLE
[App Request] <peppermint ticketing system>

### ISSUE THREAD

**Issue by NikoAnd** [WisdomSky/CasaOS-Coolstore#15]
### Brief Description:

(simple docker based ticketing system)

### Project URL:

(https://peppermint.sh/)

### Additional Information:

(Any helpful information that you want to add and to let the one who will work on adding this app know about things that need to be considered)

### Screenshots:

(Optional: Any sample screenshots of the UI)

**Comment by WisdomSky** [comment]
Added.

Note: Re-register the casaos coolstore in order to immediately see peppermint in the appstore.

![image](https://github.com/WisdomSky/CasaOS-Coolstore/assets/6792172/5eb0409d-1791-4361-96e4-d8d8723b12a1)

![image](https://github.com/WisdomSky/CasaOS-Coolstore/assets/6792172/db9f393e-3565-458a-9424-05316593ef9c)
